{% set python_min = "3.11" %}
{% set name = "imod" %}
{% set version = "1.0.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14415c7a569f280f416ee5ad59edb48eb2d3fb6f87a6a4bde2f84e2ca28ab2f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - bottleneck
    - cftime >=1.0
    - contextily >=1.0
    - cytoolz
    - dask
    - filelock
    - gdal >=3.9.2
    - geopandas
    - graphviz
    - jinja2
    - loguru
    - matplotlib-base
    - netcdf4
    - numba >=0.50
    - numpy
    - pandas
    - plum-dispatch
    - pooch
    - pydantic
    - pymetis
    - python-dateutil
    - python-graphviz
    - pyvista
    - rasterio >=1.0
    - scipy
    - scooby
    - shapely >=2.0
    - tomli >=1.1.0
    - tomli-w
    - toolz
    - tqdm
    - vtk >=9.0
    - xarray >2025.04.0
    - xugrid >=0.14.2
    - zarr

test:
  requires:
    - python {{ python_min }}
  imports:
    - imod

about:
  home: https://github.com/Deltares/imod-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Work with iMOD MODFLOW models

  description: |
    The imod Python package is an open source project to make working with
    MODFLOW groundwater models in Python easier. It builds on top of popular
    packages such as xarray, pandas, geopandas, dask,  and rasterio to provide
    a versatile toolset for working with (large) groundwater (modeling) data.
  doc_url: https://deltares.github.io/imod-python/
  dev_url: https://github.com/Deltares/imod-python

extra:
  recipe-maintainers:
    - FMSST
    - Manangka
    - JoerivanEngelen
    - visr
    - Huite
