{% set name = "imod" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e67e3202c80b64d9b45dc4d1c67f2340f1bb8847be55ea7626241007462f9b3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - affine
    - bottleneck
    - cftime >=1
    - contextily >=1
    - cytoolz
    - dask
    - declxml
    - geopandas
    - graphviz
    - python-graphviz
    - jinja2
    - matplotlib-base
    - meshzoo
    - numba >=0.50
    - numba-celltree
    - numpy
    - pandas
    - pooch
    - python-dateutil
    - pygeos
    - pyvista
    - rasterio >=1.0
    - scipy
    - shapely
    - toolz
    - tqdm
    - vtk >=9.0
    - xarray >=0.15
    - xugrid
    - zarr

test:
  imports:
    - imod

about:
  home: https://gitlab.com/deltares/imod/imod-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Work with iMOD MODFLOW models

  description: |
    The imod Python package is an addition to iMOD and iMODFLOW, intended to facilitate
    working with groundwater models from Python. It does this by supporting reading and
    writing of the different iMOD file formats to existing objects often used in Python
    data processing.
  doc_url: https://imod.xyz/
  dev_url: https://gitlab.com/deltares/imod/imod-python

extra:
  recipe-maintainers:
    - visr
    - Huite
